version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: rehab-os-postgres
    environment:
      POSTGRES_DB: clinic_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rehab-password
    ports:
      - "5434:5432"  # Different port to avoid conflict with your other project
    volumes:
      - rehab_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: rehab-os-redis
    ports:
      - "6380:6379"  # Different port to avoid conflict
    volumes:
      - rehab_redis_data:/data

  adminer:
    image: adminer:latest
    container_name: rehab-os-adminer
    ports:
      - "8088:8080"  # Different port to avoid conflict
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  rehab_postgres_data:
  rehab_redis_data: